# Generated by Django 2.2.7 on 2020-01-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Вкл')),
                ('source', models.CharField(max_length=100, verbose_name='Название источника')),
                ('source_type', models.CharField(choices=[('C', 'CLICKHOUSE'), ('M', 'MSSQL'), ('W', 'WEB')], max_length=1, verbose_name='Тип источника')),
                ('driver', models.CharField(blank=True, max_length=100, null=True, verbose_name='Драйвер')),
                ('host', models.CharField(max_length=100, verbose_name='Хост')),
                ('port', models.IntegerField(default=0, verbose_name='Порт')),
                ('instance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Экземпляр SQL-сервера')),
                ('database', models.CharField(blank=True, max_length=100, null=True, verbose_name='База данных')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пользователь')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Источники данных',
                'verbose_name_plural': 'Источники данных',
            },
        ),
        migrations.CreateModel(
            name='tile_server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Вкл')),
                ('host', models.CharField(max_length=100, verbose_name='Хост')),
                ('port', models.IntegerField(default=0, verbose_name='Порт')),
            ],
            options={
                'verbose_name': 'Тайловый сервер',
                'verbose_name_plural': 'Тайловый сервер',
            },
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layername', models.CharField(max_length=100, verbose_name='Название слоя')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Данные')),
                ('username', models.CharField(max_length=150, verbose_name='Пользователь')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Данные пользователей',
                'verbose_name_plural': 'Данные пользователей',
            },
        ),
    ]
