# Generated by Django 2.2.7 on 2020-08-25 06:36

from django.db import migrations, models
import map.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200324_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile_server',
            name='max_zoom',
            field=map.models.IntegerFieldMinMax(default=18, verbose_name='Максимальный ZOOM'),
        ),
        migrations.AddField(
            model_name='tile_server',
            name='min_zoom',
            field=map.models.IntegerFieldMinMax(default=0, verbose_name='Минимальный ZOOM'),
        ),
        migrations.AddField(
            model_name='tile_server',
            name='name',
            field=models.CharField(default='Новый', max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
