# Generated by Django 2.2.7 on 2020-10-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_tile_server_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile_server',
            name='name',
            field=models.CharField(default='New tile-server', max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
