# Generated by Django 2.2.24 on 2021-10-24 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_auto_20211011_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Доступные символы А-ЯA-Z0-9_-', regex='^([-_\\w]+)$')], verbose_name='Название'),
        ),
    ]
