# Generated by Django 2.2.7 on 2021-02-14 19:08

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ldap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Вкл')),
                ('source', models.CharField(max_length=100, unique=True, verbose_name='Название источника')),
                ('protocol', models.CharField(choices=[('ldap', 'LDAP'), ('ldaps', 'LDAPS'), ('tls', 'TLS')], default='ldap', max_length=10, verbose_name='Протокол')),
                ('host', models.CharField(help_text='IP-адрес или DNS-имя', max_length=100, verbose_name='Хост')),
                ('port', models.IntegerField(default=389, help_text='По умолчанию порты: 389 - LDAP, порт 636 - LDAPS', verbose_name='Порт')),
                ('user_dn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пользовательский DN')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пароль')),
                ('timeout', models.IntegerField(default=3, help_text='Время ожидания подключения к серверу', verbose_name='Время ожидания')),
                ('rdn', models.CharField(choices=[('cn', 'CN'), ('uid', 'UID')], default='cn', help_text='Уникальный атрибут для поиска пользователей', max_length=10, verbose_name='RDN')),
                ('search_dn', models.CharField(blank=True, default='', help_text='Ветка дерева для поиска пользователей, например: ou=users,dc=cpi,dc=dsp', max_length=100, verbose_name='DN поиска')),
                ('query', models.CharField(blank=True, default='', help_text='Запрос к LDAP-серверу, пример: <br>(&(objectClass=posixAccount)(givenName=*)(sn=*))<br> или <br> (&(objectCategory=Person)(!(UserAccountControl:1.2.840.113556.1.4.803:=2))(givenName=*)(sn=*))', max_length=255, verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'LDAP',
                'verbose_name_plural': 'LDAP',
            },
        ),
        migrations.CreateModel(
            name='proxy_group',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='proxy_user',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
