# Generated by Django 2.2.7 on 2021-02-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20210216_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldap',
            name='query',
            field=models.CharField(blank=True, default='', help_text='Запрос к LDAP-серверу, пример: <br>(&(objectClass=posixAccount)(givenName=*)(sn=*)(uid={username}))<br> или <br> (&(objectCategory=Person)(!(UserAccountControl:1.2.840.113556.1.4.803:=2))(givenName=*)(sn=*)(sAMAccountName={username}))', max_length=255, verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='ldap',
            name='rdn',
            field=models.CharField(choices=[('cn', 'cn'), ('uid', 'uid'), ('sAMAccountName', 'sAMAccountName')], default='cn', help_text='Уникальный атрибут для поиска пользователей', max_length=20, verbose_name='RDN'),
        ),
        migrations.AlterField(
            model_name='ldap',
            name='source',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
