# Generated by Django 2.2.7 on 2020-02-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='datatype',
            field=models.CharField(choices=[('int', 'Integer'), ('float', 'Float'), ('string', 'String'), ('datetime', 'DateTime'), ('ipv4', 'IPv4'), ('ipv6', 'IPv6'), ('asis', 'asIS')], default='string', max_length=10, verbose_name='Тип данных'),
        ),
        migrations.AlterField(
            model_name='types',
            name='regexp',
            field=models.CharField(default='.+', max_length=4000, verbose_name='Регулярное выражение'),
        ),
    ]
