# Generated by Django 2.2.7 on 2020-02-04 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_queries_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_query',
            fields=[
                ('v_queries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.v_queries')),
            ],
            bases=('search.v_queries',),
        ),
    ]
