# Generated by Django 2.2.7 on 2020-02-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_search_query'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search_query',
            options={'managed': False},
        ),
    ]
