# Generated by Django 2.2.7 on 2020-02-06 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20200205_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='username',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='search_query',
        ),
    ]
