# Generated by Django 2.2.7 on 2020-03-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_auto_20200225_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='protocol',
            field=models.CharField(choices=[('http', 'http'), ('https', 'https')], default='http', help_text='Протокол, актуален только для WEB шсточников', max_length=10, verbose_name='Протокол'),
        ),
    ]
