# Generated by Django 2.2.7 on 2020-03-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_sources_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='protocol',
            field=models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('http', 'По умолчанию')], default='http', help_text='Протокол, актуален только для WEB шсточников', max_length=10, verbose_name='Протокол'),
        ),
    ]
