# Generated by Django 2.2.7 on 2020-03-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0023_auto_20200307_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='group',
            field=models.ManyToManyField(blank=True, help_text='Группа(ы) для которой доступен данный запрос, если не выбранна ни одна, то доступна всем', to='auth.Group', verbose_name='Группа безопасности'),
        ),
    ]
