# Generated by Django 2.2.7 on 2020-03-29 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0029_auto_20200328_2337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='v_user_settings',
        ),
    ]
