# Generated by Django 2.2.7 on 2020-03-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0030_delete_v_user_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='source',
        ),
        migrations.AddField(
            model_name='queries',
            name='source',
            field=models.ManyToManyField(help_text='Источник к которому будет послан запрос', to='search.sources', verbose_name='Название источника'),
        ),
    ]
