# Generated by Django 2.2.7 on 2020-09-26 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0041_auto_20200926_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='name',
            field=models.CharField(default='Новый запрос', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Доступные символы А-ЯA-Z0-9_-', regex='^([-_\\w]+)$')], verbose_name='Название запроса'),
        ),
    ]
