# Generated by Django 2.2.7 on 2020-10-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0044_auto_20200928_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queries',
            old_name='response_format',
            new_name='code_type',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='xpath',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='queries',
            name='query',
            field=models.TextField(help_text='Должен содержать SQL или относительный URL к источнику данных. <br>Для передачи параметров в запрос следует включить значение {value} или {values}. <br>Для сложных SQL-запросов в начале запроса следует добавить следующие выражения:<br> SET NOCOUNT ON; SET ANSI_WARNINGS OFF;', verbose_name='SQL-запрос/URL'),
        ),
        migrations.AlterField(
            model_name='queries',
            name='request_data',
            field=models.TextField(blank=True, help_text='Работает только для источников: ClickHouse, Rest, ElasticSearch, Jarvis.<br>Для передачи параметров в запрос следует включить значение {value} или {values}.', null=True, verbose_name='Вложенные данные запроса'),
        ),
    ]
