# Generated by Django 2.2.7 on 2020-12-03 19:53

from django.db import migrations, models
import lib.validators


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0045_auto_20201014_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='code',
            field=models.TextField(blank=True, help_text='Работает только для Rest-источников:<br>\n        1) Пример XPath: /foo/bar;<br>\n        2) Пример JSONPath: $.foo.bar[*];<br>\n           $.hits.hits[*]._source[*] - пример для elasticsearch;<br>\n        3) Python-скрипт: в переменной text находится текст ответа сервера;<br>\n           Результат обработки необходимо поместить в results в формате list of dictionaries<br>\n           При ошибке скрипта данные возвращаются в текстовом виде<br>\n           Пример:<br>\n           import json<br>\n           oJson = json.loads(text)<br>\n           results = [{"mykey": item[\'tag\']} for item in oJson]\n        ', null=True, verbose_name='XPath/JSONPath/Python'),
        ),
        migrations.AlterField(
            model_name='queries',
            name='headers',
            field=models.TextField(blank=True, help_text='Работает только для источников: ClickHouse, Rest, ElasticSearch, Jarvis. Пример: {"Accept-Encoding":"gzip, deflate, br", "Connection":"keep-alive"}', null=True, validators=[lib.validators.JsonTextValidator(code='invalid_headers', message='Неверный формат JSON')], verbose_name='Дополнительные HTTP-заголовки'),
        ),
    ]
