# Generated by Django 4.1.6 on 2023-02-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0054_sources_source_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='isolation_level',
            field=models.CharField(choices=[('READ_UNCOMMITTED', 'READ UNCOMMITTED'), ('READ_COMMITTED', 'READ COMMITTED'), ('REPEATABLE_READ', 'REPEATABLE READ'), ('SERIALIZABLE', 'SERIALIZABLE')], default='READ_UNCOMMITTED', max_length=16, verbose_name='Уровень изоляции'),
        ),
    ]
