# Generated by Django 4.1.6 on 2023-03-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0055_sources_isolation_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='source_type',
            field=models.CharField(choices=[('W', 'WEB'), ('C', 'CLICKHOUSE'), ('M', 'MSSQL'), ('E', 'ELASTIC'), ('J', 'JARVIS'), ('R', 'REST'), ('PGS', 'POSTGRESQL'), ('MYS', 'MYSQL'), ('EXL', 'EXCEL'), ('CSV', 'CSV'), ('SL1', 'SQLITE'), ('SL3', 'SQLITE3')], max_length=3, verbose_name='Тип источника'),
        ),
    ]
