# Generated by Django 4.1.6 on 2023-03-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0056_sources_columns_exists_sources_encoding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='columns_exists',
            field=models.BooleanField(default=True, help_text='Только для файлов. Имена столбцов присутствуют', verbose_name='Имена столбцов'),
        ),
        migrations.AddField(
            model_name='queries',
            name='encoding',
            field=models.CharField(choices=[('ascii', 'ASCII'), ('big5', 'BIG5'), ('big5hkscs', 'BIG5HKSCS'), ('cp037', 'CP037'), ('cp273', 'CP273'), ('cp424', 'CP424'), ('cp437', 'cp437'), ('cp500', 'CP500'), ('cp720', 'CP720'), ('cp737', 'CP737'), ('cp775', 'CP775'), ('cp850', 'CP850'), ('cp852', 'CP852'), ('cp855', 'CP855'), ('cp856', 'CP856'), ('cp857', 'CP857'), ('cp858', 'CP858'), ('cp860', 'CP860'), ('cp861', 'CP861'), ('cp862', 'CP862'), ('cp863', 'CP863'), ('cp864', 'CP864'), ('cp865', 'CP865'), ('cp866', 'CP866'), ('cp869', 'CP869'), ('cp874', 'CP874'), ('cp875', 'CP875'), ('cp932', 'CP932'), ('cp949', 'CP949'), ('cp950', 'CP950'), ('cp1006', 'CP1006'), ('cp1026', 'CP1026'), ('cp1125', 'CP1125'), ('cp1140', 'CP1140'), ('cp1250', 'CP1250'), ('cp1251', 'CP1251'), ('cp1252', 'CP1252'), ('cp1253', 'CP1253'), ('cp1254', 'CP1254'), ('cp1255', 'CP1255'), ('cp1256', 'CP1256'), ('cp1257', 'CP1257'), ('cp1258', 'CP1258'), ('iso2022_kr', 'ISO2022-KR'), ('latin_1', 'LATIN-1'), ('iso8859_2', 'ISO8859-2'), ('johab', 'JOHAB'), ('koi8_r', 'KOI8-R'), ('koi8_t', 'KOI8-T'), ('koi8_u', 'KOI8-U'), ('kz1048', 'KZ1048'), ('mac_cyrillic', 'MAC-CYRILLIC'), ('utf_32', 'UTF-32'), ('utf_32_be', 'UTF-32BE'), ('utf_32_le', 'UTF-32LE'), ('utf_16', 'UTF-16'), ('utf_16_be', 'UTF-16BE'), ('utf_16_le', 'UTF-16LE'), ('utf_7', 'UTF-7'), ('utf_8', 'UTF-8'), ('utf_8_sig', 'UTF-8 BOM')], default='utf_8', help_text='Только для файлов. Кодировка файла', max_length=16, verbose_name='Кодировка'),
        ),
        migrations.AddField(
            model_name='queries',
            name='separator',
            field=models.CharField(default=',', help_text='Только для файлов. Разделитель полей в файле (tab - \\t)', max_length=8, verbose_name='Разделитель'),
        ),
        migrations.AddField(
            model_name='sources',
            name='file_directory',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Файловая директория'),
        ),
    ]
