# Generated by Django 2.2.7 on 2021-02-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldap',
            name='password',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='ldap',
            name='user_dn',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Пользовательский DN'),
        ),
    ]
