# Generated by Django 4.1.6 on 2023-04-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20210224_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldap',
            name='user_guid_param',
            field=models.CharField(choices=[('uidNumber', 'uidNumber'), ('objectGUID', 'objectGUID'), ('ibm-entityUUID', 'ibm-entityUUID'), ('dominoUNID', 'dominoUNID'), ('GUID', 'GUID'), ('nsuniqueID', 'nsuniqueID')], default='objectGUID', help_text='Название уникального параметра пользователя, для сравнения при обновлении данных пользователя', max_length=50, verbose_name='Название GUID пользователя'),
        ),
        migrations.AlterField(
            model_name='ldap',
            name='protocol',
            field=models.CharField(choices=[('ldap', 'LDAP'), ('ldaps', 'LDAPS')], default='ldap', max_length=10, verbose_name='Протокол'),
        ),
    ]
