# Generated by Django 4.1.6 on 2023-04-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_alter_proxy_group_options_user_guid_user_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldap',
            name='query',
        ),
        migrations.AddField(
            model_name='ldap',
            name='user_class',
            field=models.CharField(choices=[('posixAccount', 'posixAccount'), ('Person', 'Person'), ('inetOrgPerson', 'inetOrgPerson'), ('organizationalPerson', 'organizationalPerson')], default='Person', help_text='Название класса пользователя, для поиска данных пользователей', max_length=50, verbose_name='Название CLASS пользователя'),
        ),
        migrations.AlterField(
            model_name='ldap',
            name='user_guid_param',
            field=models.CharField(choices=[('uidNumber', 'uidNumber'), ('objectGUID', 'objectGUID'), ('ibm-entityUUID', 'ibm-entityUUID'), ('dominoUNID', 'dominoUNID'), ('GUID', 'GUID'), ('nsuniqueID', 'nsuniqueID')], default='objectGUID', help_text='Название уникального параметра пользователя, для сравнения при обновлении данных пользователей', max_length=50, verbose_name='Название GUID пользователя'),
        ),
    ]
