# Generated by Django 2.2.7 on 2020-03-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtsearch', '0002_indexes_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexes',
            name='group',
            field=models.ManyToManyField(blank=True, help_text='Группа(ы) для которой доступен данный индекс, если не выбранна ни одна, то доступна всем. ', to='auth.Group', verbose_name='Группа безопасности'),
        ),
        migrations.AlterField(
            model_name='indexes',
            name='path',
            field=models.CharField(max_length=255, unique=True, verbose_name='Путь к индексу'),
        ),
    ]
