# Generated by Django 2.2.7 on 2020-12-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtsearch', '0004_hosts_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='host',
            field=models.CharField(help_text='IP или имя хоста', max_length=100, verbose_name='Хост'),
        ),
    ]
