# Generated by Django 2.2.24 on 2021-09-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtsearch', '0005_auto_20201204_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexes',
            options={'verbose_name': 'Индексы', 'verbose_name_plural': 'Индексы'},
        ),
    ]
