# Generated by Django 2.2.7 on 2020-03-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('dtsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexes',
            name='group',
            field=models.ManyToManyField(blank=True, help_text='Группа(ы) для которой доступен данный индекс, если не выбранна ни одна, то доступна всем', to='auth.Group', verbose_name='Группа безопасности'),
        ),
    ]
