# Generated by Django 2.2.7 on 2020-12-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtsearch', '0003_auto_20200307_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='protocol',
            field=models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='http', help_text='http или https', max_length=10, verbose_name='Протокол'),
        ),
    ]
