# Generated by Django 2.2.7 on 2020-03-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile_server',
            name='protocol',
            field=models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='http', max_length=10, verbose_name='Протокол'),
        ),
        migrations.AddField(
            model_name='tile_server',
            name='url',
            field=models.CharField(blank=True, help_text='Например: /tiles/googlemap_{z}_{x}_{y}.png', max_length=255, verbose_name='URL'),
        ),
    ]
