# Generated by Django 2.2.7 on 2020-09-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200825_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile_server',
            name='priority',
            field=models.IntegerField(default=0, help_text='Указывает на порядок тайловых серверов', verbose_name='Порядок'),
        ),
    ]
