# Generated by Django 2.2.7 on 2021-02-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20201014_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tile_server',
            options={'verbose_name': 'Тайловые сервера', 'verbose_name_plural': 'Тайловые сервера'},
        ),
    ]
