# Generated by Django 2.2.24 on 2021-09-05 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0008_auto_20210224_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='user_data',
            unique_together={('layername', 'user')},
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='username',
        ),
    ]
