# Generated by Django 2.2.24 on 2021-09-23 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20210905_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Вкл')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Доступные символы А-ЯA-Z0-9_-', regex='^([-_\\w]+)$')], verbose_name='Тип идентификатора')),
                ('priority', models.IntegerField(default=0, help_text='Приоритет в соответствии с которым сортируются типы', verbose_name='Приоритет')),
                ('regexp', models.CharField(default='(?P<lat>-?\\d{1,3})[\\.\\,](?P<lat_dec>\\d{1,15})[;\\t ](?P<long>-?\\d{1,3})[\\.\\,](?P<long_dec>\\d{1,15})\\x20(P<text>)?', help_text='Основная задача состоит в том, чтобы создать регулярное выражение содержащее 4-5 именных групп:<br>\n        lat - целые числа широты; <br>\n        lat_dec - десятичные числа широты; <br>\n        long - целые числа долготы; <br>\n        long_dec - десятичные числа долготы; <br>\n        text - подпись для данной точки (если есть)', max_length=4000, verbose_name='Регулярное выражение')),
            ],
            options={
                'verbose_name': 'Координаты',
                'verbose_name_plural': 'Координаты',
            },
        ),
    ]
