# Generated by Django 2.2.24 on 2022-02-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_auto_20211024_2244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_data',
        ),
    ]
