# Generated by Django 2.2.7 on 2020-02-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20200209_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='v_queries',
        ),
        migrations.DeleteModel(
            name='v_queries_without_users',
        ),
    ]
