# Generated by Django 2.2.7 on 2020-02-13 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('search', '0010_auto_20200209_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='queries',
            name='base64',
            field=models.BooleanField(default=False, help_text='Кодирует значения в base64, для предотвращения искажения. (Можно использовать при работе с JARVIS других ЦПИ)', verbose_name='Base64'),
        ),
        migrations.AlterField(
            model_name='queries',
            name='columns',
            field=models.TextField(blank=True, help_text='Настройки результирующей таблицы в формате JSON', null=True, verbose_name='Столбцы'),
        ),
        migrations.AlterField(
            model_name='queries',
            name='cpi',
            field=models.BooleanField(default=False, help_text='Данный запрос доступен для внешних источников(других ЦПИ)', verbose_name='ЦПИ'),
        ),
        migrations.AlterField(
            model_name='queries',
            name='position',
            field=models.IntegerField(default=0, help_text='Порядок, указывающий на последовательность вывода результатов запросов на экран (по возрастанию) ', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='queries',
            name='query',
            field=models.TextField(help_text='Должен содержать SQL или HTTP запрос к источнику данных. Должен содержать значение {value} или {values}', verbose_name='SQL-запрос'),
        ),
        migrations.AlterField(
            model_name='queries',
            name='script',
            field=models.TextField(blank=True, help_text='Python-скрипт, позволяющий обрабатывать выделенные по регулярным выражениям из текста значения, перед тем как они будут помещены в текст запроса. Массив values содержит значения(тип str). Пример: values = list( map(lambda x:x[:3], values))', null=True, verbose_name='Скрипт предобрабоки'),
        ),
        migrations.AlterField(
            model_name='queries',
            name='source',
            field=models.ForeignKey(help_text='Источник к которому будет послан запрос', on_delete=django.db.models.deletion.CASCADE, to='search.sources', verbose_name='Название источника'),
        ),
        migrations.AlterField(
            model_name='queries',
            name='timeout',
            field=models.IntegerField(default=30, help_text='Время ожидания, после которого запрос прекратит исполнятся', verbose_name='Время ожидания'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='driver',
            field=models.CharField(blank=True, help_text='Например для MS SQL Server: {ODBC Driver 17 for SQL Server}', max_length=100, null=True, verbose_name='Драйвер'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='host',
            field=models.CharField(help_text='IP-адрес или DNS-имя', max_length=100, verbose_name='Хост'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='password',
            field=models.CharField(blank=True, help_text='Используется для авторизации на удаленных источниках', max_length=50, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='user',
            field=models.CharField(blank=True, help_text='Используется для авторизации на удаленных источниках', max_length=50, null=True, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='types',
            name='priority',
            field=models.IntegerField(default=0, help_text='Приоритет в соответствии с которым сортируются типы', verbose_name='Приоритет'),
        ),
    ]
