# Generated by Django 2.2.7 on 2020-02-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_auto_20200223_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='queries',
            name='query',
            field=models.TextField(help_text='Должен содержать SQL или HTTP запрос к источнику данных. <br>Для передачи параметров в запрос следует включить значение {value} или {values}. <br>Для сложных SQL-запросов в начале запроса следует добавить следующие выражения:<br> SET NOCOUNT ON; SET ANSI_WARNINGS OFF;', verbose_name='SQL-запрос'),
        ),
        migrations.AlterField(
            model_name='queries',
            name='script',
            field=models.TextField(blank=True, help_text='Python-скрипт, позволяющий обрабатывать выделенные по регулярным выражениям из текста значения, перед тем как они будут помещены в текст запроса.  При любой ошибке в скрипте он игнорируется.<br>Массив values содержит массив значений(тип str). Массив sources соделжит параметры подключения к источникам данных.<br>Пример: values = list( map(lambda x:x[:3], values))', null=True, verbose_name='Скрипт предобрабоки'),
        ),
    ]
