# Generated by Django 2.2.7 on 2020-03-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0025_auto_20200307_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='name',
            new_name='query',
        ),
    ]
