# Generated by Django 2.2.7 on 2020-03-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0027_auto_20200328_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconfig',
            options={'verbose_name': 'Настройки пользователей', 'verbose_name_plural': 'Настройки пользователей'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'Настройки запросов пользователей', 'verbose_name_plural': 'Настройки запросов пользователей'},
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='skin',
            field=models.CharField(max_length=20, verbose_name='Скин'),
        ),
    ]
