# Generated by Django 2.2.7 on 2020-03-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0028_auto_20200328_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='query',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='userConfig',
        ),
        migrations.DeleteModel(
            name='userSettings',
        ),
    ]
