# Generated by Django 2.2.7 on 2020-03-29 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0032_auto_20200329_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Вкл')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.queries', verbose_name='Название запроса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки запросов пользователей',
                'verbose_name_plural': 'Настройки запросов пользователей',
            },
        ),
        migrations.AddField(
            model_name='queries',
            name='user',
            field=models.ManyToManyField(through='search.user_queries', to=settings.AUTH_USER_MODEL),
        ),
    ]
