# Generated by Django 2.2.7 on 2020-05-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0033_auto_20200329_2128'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='queries',
            unique_together={('typename', 'name')},
        ),
    ]
