# Generated by Django 2.2.7 on 2020-08-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0034_auto_20200506_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='source_type',
            field=models.CharField(choices=[('C', 'CLICKHOUSE'), ('M', 'MSSQL'), ('W', 'WEB'), ('E', 'ELASTIC'), ('J', 'JARVIS'), ('R', 'REST')], max_length=1, verbose_name='Тип источника'),
        ),
    ]
