# Generated by Django 2.2.7 on 2020-08-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0035_auto_20200825_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='headers',
            field=models.TextField(blank=True, help_text='Работает только для источников: ClickHouse, Rest, ElasticSearch, Jarvis. Пример: [{"Accept-Encoding":"gzip, deflate, br"}, {"Connection":"keep-alive"}]', null=True, verbose_name='Дополнительные HTTP-заголовки'),
        ),
        migrations.AddField(
            model_name='queries',
            name='method',
            field=models.CharField(blank=True, choices=[('CONNECT', 'CONNECT'), ('DELETE', 'DELETE'), ('GET', 'GET'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('PATCH', 'PATCH'), ('POST', 'POST'), ('PUT', 'PUT'), ('TRACE', 'TRACE')], default='GET', help_text='Работает только для источников: ClickHouse, Rest, ElasticSearch, Jarvis', max_length=10, null=True, verbose_name='Тип запроса'),
        ),
        migrations.AddField(
            model_name='queries',
            name='request_data',
            field=models.TextField(blank=True, help_text='Работает только для источников: ClickHouse, Rest, ElasticSearch, Jarvis.', null=True, verbose_name='Вложенные данные запроса'),
        ),
        migrations.AddField(
            model_name='queries',
            name='response_format',
            field=models.CharField(blank=True, choices=[('CONNECT', 'CONNECT'), ('DELETE', 'DELETE'), ('GET', 'GET'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('PATCH', 'PATCH'), ('POST', 'POST'), ('PUT', 'PUT'), ('TRACE', 'TRACE')], default='json', help_text='Работает только для Rest-источников', max_length=10, null=True, verbose_name='Формат возвращаемых данных'),
        ),
        migrations.AddField(
            model_name='queries',
            name='xpath',
            field=models.TextField(blank=True, help_text='Работает только для Rest-источников', null=True, verbose_name='XPath(JSONPath)'),
        ),
    ]
