# Generated by Django 2.2.7 on 2020-09-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0037_auto_20200825_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='columns',
        ),
    ]
