# Generated by Django 2.2.7 on 2020-09-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0038_remove_queries_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': 'Идентификаторы', 'verbose_name_plural': 'Идентификаторы'},
        ),
        migrations.DeleteModel(
            name='info',
        ),
    ]
