# Generated by Django 2.2.7 on 2020-09-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0039_auto_20200926_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='datatype',
            field=models.CharField(choices=[('int', 'Integer'), ('float', 'Float'), ('string', 'String'), ('datetime', 'Date'), ('datetime', 'DateTime'), ('ipv4', 'IPv4'), ('ipv6', 'IPv6'), ('asis', 'asIS')], default='string', help_text='В каком формате значения будут подставлены в запрос', max_length=10, verbose_name='Тип данных'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='source',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название источника'),
        ),
    ]
