# Generated by Django 2.2.7 on 2020-09-26 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0040_auto_20200926_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='name',
            field=models.CharField(default='Новый запрос', max_length=255, validators=[django.core.validators.RegexValidator(message='Hashtag doesnt comply', regex='^([-_\\w]+)$')], verbose_name='Название запроса'),
        ),
    ]
