# Generated by Django 2.2.7 on 2020-09-26 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0042_auto_20200926_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='typename',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Доступные символы А-ЯA-Z0-9_-', regex='^([-_\\w]+)$')], verbose_name='Тип идентификатора'),
        ),
    ]
