# Generated by Django 2.2.24 on 2021-09-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0047_auto_20210213_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='script',
        ),
        migrations.AlterField(
            model_name='queries',
            name='code_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('json', 'Json'), ('xml', 'XML'), ('python', 'Python')], default='', help_text='Работает только для Rest-источников<br>Работает в паре с полем XPath/JSONPath/Python-скрипт', max_length=10, null=True, verbose_name='Обработка ответа сервера'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='port',
            field=models.IntegerField(default=80, verbose_name='Порт'),
        ),
    ]
