# Generated by Django 2.2.24 on 2021-09-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0048_auto_20210905_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='source_type',
            field=models.CharField(choices=[('C', 'CLICKHOUSE'), ('M', 'MSSQL'), ('W', 'WEB'), ('E', 'ELASTIC'), ('J', 'JARVIS'), ('R', 'REST')], max_length=3, verbose_name='Тип источника'),
        ),
    ]
