# Generated by Django 2.2.24 on 2021-10-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0050_auto_20211011_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='query',
            field=models.TextField(help_text='Должен содержать SQL или относительный URL к источнику данных. <br>Допустимые параметры: {{value}},{{values}},{{values_list}},{{username}},{{date_from}},{{date_to}},{{now}},{{original_value}},{{original_values_list}},{{groups_list}}. <br>Директиву USE не использовать;<br>При необходимости, в начале запроса следует добавить выражения:<br> SET ANSI_WARNINGS OFF;', verbose_name='SQL-запрос/URL'),
        ),
    ]
